import { SchoolManagementSystem } from "./src/SchoolManagementSystem";
import { Exam } from "./src/Exam";
import { Grade } from "./src/Grade";
import { Subject } from "./src/Subject";
import { Teacher } from "./src/Teacher";
import { Room } from "./src/Room";
import { Classroom } from "./src/Classroom";
import { GoogleClassroom } from "./src/GoogleClassroom";
import { Assignment } from "./src/Assignment";
import { StudyMaterial } from "./src/StudyMaterial";
import { Feedback } from "./src/Feedback";
import { Department } from "./src/Department";
import { TimeTable } from "./src/TimeTable";
import { Student } from "./src/Student";
import { Admin } from "./src/Admin";


// Example Usage
const school = new SchoolManagementSystem("Springfield High", "123 Main St", "contact@springfieldhigh.com", "SCH001");
const mathDept = new Department("Mathematics");
const teacher = new Teacher(1, "John", "Doe", "john.doe@example.com", "password", "1234567890", mathDept);
const timetable = new TimeTable(new Date("2025-06-04T10:00:00"), "Room 101", "Math", []);
const googleClassroom = new GoogleClassroom();
const student = new Student(2, "Jane", "Smith", "jane.smith@example.com", "password", "0987654321", timetable, googleClassroom);
const admin = new Admin(3, "Admin", "User", "admin@example.com", "password", "5555555555");
const classroom = new Classroom("Math 101");
const subject = new Subject(1, "MATH101", [teacher]);
const room = new Room("Room 101", "Building A");
const exam = new Exam([subject], "Midterm", new Date("2025-06-04T10:00:00"), room);
const studyMaterial = new StudyMaterial("Lesson 1", ["Content 1", "Content 2"]);
const assignment = new Assignment(1, "Homework 1", "Complete exercises", new Date("2025-06-05"), "MATH101");
const grade = new Grade(1, 2, 85, "Good effort");
const examScore = new ExamScore(exam, 90);
const subjectResult = new SubjectResult(subject);
const studentExamReport = new StudentExamReport(student);
const feedback = new Feedback(1);
const notification = new Notification();

timetable.addExamSchedule(exam);
classroom.addTeacher(teacher);
classroom.addStudent(student);
classroom.addStudyMaterial(studyMaterial);
classroom.addAssignment(assignment);
classroom.addGrade(grade);
teacher.uploadStudyMaterial(classroom, studyMaterial);
teacher.uploadAssignment(classroom, assignment);
teacher.returnGrade(classroom, grade);
student.submitAssignment(assignment, classroom);
student.downloadMaterial(studyMaterial, classroom);
admin.addSubject(subject);
admin.addTeacher(teacher);
admin.assignSubjectToStudents(subject, student);
admin.assignTeacherToStudents(teacher, student);
subjectResult.addExamScore(examScore);
studentExamReport.addSubjectResult(subjectResult);
admin.addStudentReport(studentExamReport);
feedback.addCommentToSubject(1, "Great subject!");
feedback.addRatingToSubject(1, "5/5");
notification.alertMessageBeforeClass5Minute(timetable);

console.log(teacher.login("john.doe@example.com", "password"));
console.log(student.viewTimetable().getSubject());
console.log(school.viewSchoolDetails());
console.log(`Grade: ${grade.getLetterGrade()}`);